using System.Runtime.InteropServices;

namespace Refrigerator;

public static class Brand
{
    private const string LogoBase64 = "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAABgFBMVEXx/v5wiaFth514lKjR5+2Lp7etyNOYtsfc8vfG3OSCm6y71+S50tqiu8qXsruQrcHD2d13kZ7g7vNof5R+oLaew9Ovy+IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC4mxJiAAAAgHRSTlP//////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF9quxYAAAReSURBVHja7VqLbusgDK0x5pGQtNt9/P+nXjAhpNO60tKCdIW3SZu0xgc/jh/kdBoyZMiQIUOGDPkvxUjZVb9U62J7AlAISB0RGI0AoDt6QU0CABfTLwbWyZtgUv1McFmDE6aOYXAh7GwDRR6AwH4IzBLCQMDSLxDZCQL6xYELTgCx9GQDDoOOfKRReDm/zKlOkXowDCAgcK9RH47zSxSwqzEmFyUhQNAL1NtVhEfBfQtIpc+LmyWDMCRCUZD1GRXU+yepksAL/zqRYgQO/R+ilo0cRvUF9VWx0xlC1Erhk5U+cKy+5Pgn6blnAwDEcDVDr/KB3J43F/zvCsw9BxPM7JEaH0jk8CN5KjPADgDPcvu4b46q9eNcRH2snyi6jDKAiiCgkHylNowVWFoURwAB09PNmWJrisIH0FZ8NOxRWAlAfgguqfOpHIBi3ggmCJ+yUAVg5QQQhTEkpw2AN0GyQAyLc0UEBq8W4jdTqv9z+KDiXxiAqouAuThiAwCKVYh5c45NEcxPp8BjxWzh4zJjRNr4E2nhWSb0Iej1JwPI+wOvxS89mObzi8lUeEBg9K8vc3iXjrkLPBicfVIcxN96QMQDyTVWOVVChcniRkdmxmdDYGKdNjUELPp+Im4McJo1B0AxjX2fhOwBE6OxAAFX39A6KKVjBlYYQO4NnQuakYgL3fJzGMbmQfDZobSPuPEwPrZOBiDL57sz6ijc9CYAFdOhTWHHJTkQS7SJvr+b2JxfOZ3uACwDUByWkPLyh4kMt67M/1TN598AwEwMP67I/FzKUaPqmkFILgj5yCTE5r1fm4wfolbSrnIekDv1eEqMOy+s73EfzoKQdWb1wWw2AMXVuR4A5FooedSSsbS0Gq459gR8HqtTyK9zKwCX2A/pIzU+0KC9CID/ctkizDBzYxf45o776yVxW7sNC31EBAIQmVmYYRtu/tJaQGRpaoDcBx0hfGsAq7VWb+EnheJa6Hb3uNh3QLjQFYQbNLywnZDeYgR3gID2h73ATfvUinHrShN+4HTjhIb2NuxtKSKtUsreLBp7puDnqYNwqxjT5VeP+wG3G6BlqczyiUcA0B4AHcjSA5Bd9afhvHEAZqb2v8oO+g8WaNcwHnq0KwDUVL9BuAIgRLt2KTPQFYC2HkgO2GlAtGtYc5O8j8IlK5wXM0BSDwiJhlpek9oUgUg6TsO+ErRkARcB4G9tpXQEr7qgK29Yt3WU3BZ0ouXQ5GWNBtDHsantzIDHnWQHALEPPeeIEOUXG6+ZXNkD+9JwgcbNgIsc/De3BY0BxKjPcwIvk5sC+FL921tAwLH6h1cV2r6toXh50hMAXK2Lwi4T6i6pnwEQLySlF8XL8ZZE5GIl1HLWZ9J6ilfMDYlou6kHTPci/NOyGlNWvPdFTd9Z2u6nQKTv5i9NqWkHkJZp1HgqweNM6JFQ26HAZ8IEeX0E5Nq/wyqtdUppmhC3F5c6Se8XuYcMGTJkyJAhQ4bUyT+zPRjFf55B0gAAAABJRU5ErkJggg==";

    public static Image Image()
    {
        using var ms = new MemoryStream(Convert.FromBase64String(LogoBase64));
        using var img = System.Drawing.Image.FromStream(ms);
        return new Bitmap(img);
    }

    public static Icon Icon()
    {
        using var bmp = new Bitmap(Image(), new Size(64,64));
        var handle = bmp.GetHicon();
        try { return (Icon)System.Drawing.Icon.FromHandle(handle).Clone(); }
        finally { DestroyIcon(handle); }
    }

    [DllImport("user32.dll")]
    private static extern bool DestroyIcon(IntPtr hIcon);
}
